# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-04 12:40
from __future__ import unicode_literals

from django.db import migrations

def update_partner(apps, schema_editor):
    Orders = apps.get_model('order', 'Order')
    for order in Orders.objects.all():
        if not order.partner:
        	site = order.site
        	site_configuration = site.siteconfiguration
        	order.partner = site_configuration.partner
        	order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_partner'),
    ]

    operations = [
    	migrations.RunPython(update_partner),
    ]
